### ISSUE TITLE
Improve packet locality using SO_ATTACH_REUSEPORT_CBPF or SO_ATTACH_REUSEPORT_EBPF

### ISSUE THREAD

**Issue by wangbin579** [session-replay-tools/cetus#108]
内核4.6以后支持SO_ATTACH_REUSEPORT_EBPF或者SO_ATTACH_REUSEPORT_CBPF。
利用这个来提升cetus多进程版本性能，预期提升性能30～50%

**Comment by lazio579** [comment]
移植一个dpdk 的版本
移植到ans 上
这样可以完全避免ip  协议栈的影响

**Comment by lazio579** [comment]
如果用基于dpdk的tcp/ip协议栈，预计性能提升100%以上
