### ISSUE TITLE
macos 已经安装了tcmalloc，cmake没问题，但是编译报错,

### ISSUE THREAD

**Issue by sunashe** [session-replay-tools/cetus#172]
[  7%] Built target ev-cetus
[  7%] Built target lemon
[  7%] Linking C shared library libsqlparser.dylib
Undefined symbols for architecture x86_64:
  "_cJSON_Delete", referenced from:
      _sql_filter_vars_load_str_rules in sql-filter-variables.c.o
  "_cJSON_GetObjectItem", referenced from:
      _sql_filter_vars_load_str_rules in sql-filter-variables.c.o
  "_cJSON_Parse", referenced from:
      _sql_filter_vars_load_str_rules in sql-filter-variables.c.o
  "_g_ascii_strdown", referenced from:
      _str_case_hash in sql-filter-variables.c.o
  "_g_assertion_message_expr", referenced from:
      _sql_set_variable in sql-operation.c.o
      _sql_filter_vars_load_default_rules in sql-filter-variables.c.o
      _sql_filter_vars_shard_load_default_rules in sql-filter-variables.c.o
  "_g_free", referenced from:
      _sql_expr_free in sql-expression.c.o
      _sql_select_free in sql-expression.c.o
      _sql_column_free in sql-expression.c.o
      _sql_delete_free in sql-expression.c.o
      _sql_update_free in sql-expression.c.o
      _sql_table_reference_free in sql-expression.c.o
      _sql_insert_free in sql-expression.c.o
      ...
  "_g_hash_table_destroy", referenced from:
      _sql_filter_vars_destroy in sql-filter-variables.c.o
  "_g_hash_table_lookup", referenced from:
      _sql_filter_vars_is_silent in sql-filter-variables.c.o
      _sql_filter_vars_is_allowed in sql-filter-variables.c.o
  "_g_hash_table_new_full", referenced from:
      _sql_filter_vars_load_str_rules in sql-filter-variables.c.o
  "_g_hash_table_remove_all", referenced from:
      _sql_filter_vars_reload_str_rules in sql-filter-variables.c.o
  "_g_hash_table_replace", referenced from:
      _sql_filter_vars_load_str_rules in sql-filter-variables.c.o
  "_g_list_append", referenced from:
      _sql_filter_vars_load_str_rules in sql-filter-variables.c.o
  "_g_list_free_full", referenced from:
      _sql_variable_free in sql-filter-variables.c.o
  "_g_log", referenced from:
      _sql_statement_free in sql-expression.c.o
      _sql_delete in sql-operation.c.o
      _sql_update in sql-operation.c.o
      _sql_insert in sql-operation.c.o
      _sql_start_transaction in sql-operation.c.o
      _sql_commit_transaction in sql-operation.c.o
      _sql_rollback_transaction in sql-operation.c.o
      ...
  "_g_malloc0", referenced from:
      _sql_token_dup in sql-expression.c.o
      _sql_expr_new in sql-expression.c.o
      _sql_expr_dup in sql-expression.c.o
      _parser_set_value in sql-property.c.o
      _sql_context_append_msg in sql-context.c.o
  "_g_malloc0_n", referenced from:
      _sql_column_new in sql-expression.c.o
      _sql_select_new in sql-expression.c.o
      _sql_delete_new in sql-expression.c.o
      _sql_update_new in sql-expression.c.o
      _sql_insert_new in sql-expression.c.o
      _sql_drop_database_new in sql-expression.c.o
      _sql_src_list_append in sql-expression.c.o
      ...
  "_g_ptr_array_add", referenced from:
      _sql_expr_list_append in sql-expression.c.o
      _sql_column_list_append in sql-expression.c.o
      _sql_src_list_append in sql-expression.c.o
      _sql_id_list_append in sql-expression.c.o
  "_g_ptr_array_free", referenced from:
      _sql_expr_free in sql-expression.c.o
      _sql_expr_list_free in sql-expression.c.o
      _sql_column_list_free in sql-expression.c.o
      _sql_src_list_free in sql-expression.c.o
      _sql_id_list_free in sql-expression.c.o
  "_g_ptr_array_new_with_free_func", referenced from:
      _sql_expr_list_append in sql-expression.c.o
      _sql_column_list_append in sql-expression.c.o
      _sql_src_list_append in sql-expression.c.o
      _sql_id_list_append in sql-expression.c.o
  "_g_str_hash", referenced from:
      _str_case_hash in sql-filter-variables.c.o
  "_g_strdup", referenced from:
      _sql_expr_dup in sql-expression.c.o
      _sql_filter_vars_load_str_rules in sql-filter-variables.c.o
  "_g_strfreev", referenced from:
      _sql_filter_vars_is_silent in sql-filter-variables.c.o
      _sql_filter_vars_is_allowed in sql-filter-variables.c.o
  "_g_string_append", referenced from:
      _sql_construct_select in sql-construction.c.o
      _sql_construct_join in sql-construction.c.o
      _sql_construct_insert in sql-construction.c.o
      _sql_append_expr in sql-construction.c.o
  "_g_string_append_len", referenced from:
      _sql_construct_select in sql-construction.c.o
      _append_sql_expr in sql-construction.c.o
      _sql_construct_insert in sql-construction.c.o
  "_g_string_free", referenced from:
      _sql_construct_select in sql-construction.c.o
      _sql_construct_insert in sql-construction.c.o
      _sql_append_expr in sql-construction.c.o
  "_g_string_insert_c", referenced from:
      _g_string_append_c_inline in sql-construction.c.o
  "_g_string_new", referenced from:
      _sql_construct_select in sql-construction.c.o
  "_g_strsplit_set", referenced from:
      _sql_filter_vars_is_silent in sql-filter-variables.c.o
      _sql_filter_vars_is_allowed in sql-filter-variables.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libsqlparser.dylib] Error 1
make[1]: *** [lib/CMakeFiles/sqlparser.dir/all] Error 2
make: *** [all] Error 2

**Comment by lynnlz** [comment]
ubuntu16.04 支持吗？

**Comment by lynnlz** [comment]
> mac os不支持

ubuntu16.04 支持吗？
也报一大堆编译错误
