### ISSUE TITLE
docker镜像启动方式

### ISSUE THREAD

**Issue by zhanghongjie** [session-replay-tools/cetus#184]
请问docker镜像方式除了root用户启动注意点，还有其他的么，发现几个mysql没启动成功

**Comment by tsthght** [comment]
MySQL没有启动成功？能否将MySQL的报错日志贴一下？

**Comment by zhanghongjie** [comment]
![image](https://user-images.githubusercontent.com/3624314/56482010-6de47f80-64f4-11e9-8463-d61fc6e05f71.png)
重新尝试过，发现主从库连不上，其他正常

**Comment by tsthght** [comment]
我按步骤复现，并没有复现出来问题。方便加一下QQ: 781181214 进一步沟通下么？
