### ISSUE TITLE
cetus+mha，主库不达，切换主库问题

### ISSUE THREAD

**Issue by wukai1211** [session-replay-tools/cetus#188]
按照文档cetus+mha搭建好了，相关都替换了，故障测试，当主库连接不上是，mha会自动切换主库。cetus默认也会自动切换主库吗？还是需要自己写一个脚本把脚本放在mha的master_ip_failover_script上执行在cetus-admin中修改backends来实现对主库的切换的脚本？
我默认是cetus会自动切换主库，不需要自己写脚本，但是实际测试过程中，把主库停止后，backends表显示主库状态是up，倒是从库全部down了。
停止主库前，如下图：
![image](https://user-images.githubusercontent.com/12652827/58367007-5beb6780-7f0c-11e9-9013-92ab9089a764.png)
停止主库后，如下图：
![image](https://user-images.githubusercontent.com/12652827/58367015-702f6480-7f0c-11e9-9d0b-ecb8e7e361c5.png)
cetus里日志里也没有看到任何切换主库的日志记录。一直就是报连接不上原主库：
![image](https://user-images.githubusercontent.com/12652827/58367043-c2708580-7f0c-11e9-9665-2a8446c3550a.png)
请问，这问题出在哪里？是cetus不会自动切换主库，还是我哪里的配置出问题了，还是我上面说的这个切换需要自己写脚本，在cetus-admin中修改backends来实现对主库的切换？

**Comment by wukai1211** [comment]
好吧，我找到原因了。原因是因为装mha的manger节点的服务器没有装msyql客户端。导致mha在进行切换主库执行的这个命令：exec command: /usr/bin/mysql -h192.168.0.85 -uadmin -P7001 -padmin  -e " update backends set state='up' , type='rw' where address='192.168.0.34:3306';"没有成功。但是mha日志中没有体现其执行失败的的日志。cetus中也没有。建议增加这个日志。至少在cetus+mha说明文档中增加说明必须mha所在的节点必须安装mysql客户端。

**Comment by zskylark** [comment]
请问cetus+mha用在生产环境是否可靠？
