### ISSUE TITLE
问题列表

### ISSUE THREAD

**Issue by wangbin579** [session-replay-tools/cetus#193]
存在问题列表：
1、fast stream问题 ××××××××××××××××
已经解决

2、主从延迟检测 ××××××××××
写频繁的场合，可能写不进去，导致cetus主从延迟检测出问题，而实际MySQL主从延迟并没有问题
原因是用户应用的存储过程都路由给主库，cpu 100%，导致主从检测失败

3、MySQL 8客户端无法访问cetus，报：client charset is not supported
需要支持所有字符集

4、cetus还不能采用MySQL新的认证方式访问MySQL 8

5、cetus在centos 7.6，内核3.10，gcc为4.8.5版本，第一次没有问题，而第二次出现
      No rule to make target ‘/usr/local/lib/libgnutls.a',needed by 'src/libmysql-chassis.so'
      不确定是否跟安装目录和环境变量有关系

6、prepare语句可能还有问题

7、从库如果关闭，可以重新连接其它后端，从而对用户屏蔽后端错误

8、一对多连接，大量结果集数据合并，来不及写导致内存暴增

9、支持用户选择访问某一个从库

10、如果conf默认配置用户名在user.conf不存在，则cetus不会自动退出，导致了启动烦恼

11、去除读写分离版本中的proxy_c_read_query_result部分代码：
case INJ_ID_CHANGE_DB下面的设置default db已经没有存在的意义，早就在前面设置了

12、sum/count不支持（哪怕是不同的字段），需要在文档中说明一下

13、集成多个独立的主从

14、同一个vdb id情况下，不同属性作为分片键是不支持的，这方面文档可能没有说清楚

15、如果主库设置readonly，会导致主从检测的语句写不进去？

16、远程配置库，更改字符集成utf8mb4，查看是否生效？
       是因为cetus返回给客户端的greet数据包里面字符集为utf8，应该改成配置文件中的默认字符集

17、大sql超过16M，目前不支持

18、ER_LOCK_WAIT_TIMEOUT这种不应该导致隐式回滚（针对分库版本）

19、支持从库按权重分配，以支持硬件条件不一的场景

20、reduce-connections=true设置后，show variables里看是false，这个不应该

21、mha切换的时候，错写ip地址导致如下现象：
如果新主IP错填写成老主了，这时候不会切，但是rw就改成ro了

22、 SET autocommit=0之后， SET SQL_SELECT_LIMIT=1就会生效了，本来这个是silent的。××××××××

23、全量日志有bug
用户描述如下：
"打开全量日志的时候，好像会导致cetus的时区出现问题，报这个错。
报的时候，日志看是所有的slave都被判断延迟8小时。所以应该不是slave的时区问题，而是cetus的时区问题。
打开全量日志，cetus日志里面能看到每小时平均偶尔发一次，关闭全量日志就没了"

24、mha脚本存在缺陷，如果mysql client没有安装，则不会报错

25、原来改的mha有个问题，能切出无主的状态。

**Comment by UNSCMasterChief** [comment]
jdbc 还是不能连接 报 client charset is not supported
mysql version 8.0
![image](https://github.com/session-replay-tools/cetus/assets/166593116/174c6edc-05de-4dd5-8b27-e40afc57febf)

**Comment by net592** [comment]
:-) 您好，收到了 ，尽快恢复
