### ISSUE TITLE
报错This sql_mode is not supported. 

### ISSUE THREAD

**Issue by mykioer** [session-replay-tools/cetus#198]
`(message) plugins/proxy/proxy-plugin.c:1271 SQL unsupported: This sql_mode is not supported. while parsing: SET SESSION sql_mode =
                                        REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(
                                        @@sql_mode,
                                        "STRICT_ALL_TABLES,", ""),
                                        ",STRICT_ALL_TABLES", ""),
                                        "STRICT_ALL_TABLES", ""),
                                        "STRICT_TRANS_TABLES,", ""),
                                        ",STRICT_TRANS_TABLES", ""),
                                        "STRICT_TRANS_TABLES", "") for con:0x1cad760, clt:10.0.22.155:44635`

**Comment by wangbin579** [comment]
这种不支持，只能通过静默变量来规避
