### ISSUE TITLE
分库版本包含所有读写分离版本功能，向咨询下为啥要特地弄两个版本？期待回复，谢谢

### ISSUE THREAD

**Issue by y123456yz** [session-replay-tools/cetus#199]
分库版本包含所有读写分离版本功能，向咨询下为啥要特地弄两个版本？期待回复，谢谢
是因为prepare语句功能所以单独加了个读写分离版本？
@wangbin579

**Comment by lazio579** [comment]
首先，解析器不同，编译时不好整合在一起。其次，中间件分库功能会被淘汰，以后会被剥离掉。

**Comment by zskylark** [comment]
> 首先，解析器不同，编译时不好整合在一起。其次，中间件分库功能会被淘汰，以后会被剥离掉。

为何中间件分库会被淘汰？
