### ISSUE TITLE
update set 加上子查询就不可以

### ISSUE THREAD

**Issue by zch513430014** [session-replay-tools/cetus#201]
UPDATE table1 AS d INNER JOIN (
SELECT a.id FROM  `table1` AS a INNER JOIN table2 AS b ON a.`uid` = b.`uid` AND a.`appid` = b.`appid` 
) AS sub ON d.id = sub.id SET channel = 'abcdefg'

错误信息:near "INNER": syntax error
但是我去单库上面执行就可以。

**Comment by lazio579** [comment]
目前这种功能确实不支持，静等我们的分布式数据库产品，就不会有这些兼容性问题了
