### ISSUE TITLE
本地在admin中执行config reload 超时

### ISSUE THREAD

**Issue by zch513430014** [session-replay-tools/cetus#202]
我用的是分库版本
我本地没有对cetus做任何操作
只是修改了sharding.conf 文件,增加了一个single table
想reload 但是不行。
线上时时刻刻都有数据进来，不敢重启。

**Comment by zch513430014** [comment]
提示:update remote settings timeout

**Comment by zskylark** [comment]
分库版本靠谱不？想在生产平台用。但是我看到前面的issue里有人回复说分库会被淘汰？不知什么原因。

**Comment by zch513430014** [comment]
@zskylark  我们用分库只是为了储存用户设备登陆信息。用了半年多，还是稳定，而且一般用分库的话，并不是拿来做实时查询这块。估计那些说淘汰的人，应该可能是用日志比如elk或者其它方案来存储日者这块信息，然后用来做离线计算吧

**Comment by lazio579** [comment]
因为MySQL xa有bug

**Comment by lazio579** [comment]
> 
> 
> 提示:update remote settings timeout

这个最好弄清楚超时的原因。

一般可以利用lvs外加cetus admin相关命令来配合升级
