### ISSUE TITLE
jdbc 操作中间件报错 SET of net_write_timeout is not supported

### ISSUE THREAD

**Issue by zch513430014** [session-replay-tools/cetus#210]
我在使用阿里云datawork数据同步的时候，报错
SET of net_write_timeout is not supported.
阿里云那边的操作应该是用了mysql session回话这块功能,所以他们有很多操作,都是先执行set xxx的命令后,然后执行,cetus支持吗？

**Comment by wangbin579** [comment]
需要设置静默变量，请参考：
https://github.com/session-replay-tools/cetus/blob/master/doc/cetus-rw-profile.md
