### ISSUE TITLE
为什么登录会被拒绝？

### ISSUE THREAD

**Issue by liyu76** [session-replay-tools/cetus#211]
cetus版本：cetus-2.3.7

1、主库账户信息
mysql> select user,host from mysql.user;
+---------------+-----------+
| user          | host      |
+---------------+-----------+
| repl          | %         |
| root          | %         |
| root          | localhost |
+---------------+-----------+

2、proxy.conf 配置：
plugins=proxy,admin
proxy-address=0.0.0.0:3306
proxy-backend-addresses=192.168.174.71:3306
proxy-read-only-backend-addresses=192.168.174.72:3306,192.168.174.73:3306
admin-address=0.0.0.0:7001
admin-username=admin
admin-password=admin
......

3、user.json配置：
{
    "users": [
        { "user": "root", "client_pwd": "000000", "server_pwd": "000000" }
    ]
}

\# cetus --defaults-file=conf/proxy.conf
\# mysql -h 192.168.174.74 -uroot -p
Enter password:
ERROR 1045 (28000): Access denied for user 'root'@'192.168.174.74:53769' (using password: YES)

直接访问主库没问题：
\# mysql -h 192.168.174.71 -uroot -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 11
Server version: 5.7.30-log MySQL Community Server (GPL)

4、登录管理没问题
\# mysql -h 192.168.174.74 -P7001 -uadmin -padmin
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
Server version: 5.7 admin Cetus proxy

**Comment by wangbin579** [comment]
这种报错是权限方面的问题

**Comment by liyu76** [comment]
> 
> 
> 这种报错是权限方面的问题

问题找到了，是密码的问题，密码不能全是数字

**Comment by liyu76** [comment]
问题已解决
