### ISSUE TITLE
cetus 查看后端服务器，slave 的 state 一直是 unknown

### ISSUE THREAD

**Issue by liyu76** [session-replay-tools/cetus#212]
centus 查看后端服务器，master 的 state 显示正常状态：up，但是 slave 的 state 总是显示： unknown
这个问题怎么解决？

**Comment by wangbin579** [comment]
一般是权限问题或者没有按照文档要求配置心跳表

**Comment by wangbin579** [comment]
上一个登入问题找到根源了吗 ？

**Comment by liyu76** [comment]
谢谢，配置心跳表后状态显示正常
