### ISSUE TITLE
cetus负载多个从库时，是什么机制或者算法保证多个从库压力基本保持一致的？

### ISSUE THREAD

**Issue by wwwwwwchun** [session-replay-tools/cetus#215]
您好，我想问一下，在一主多从的架构中，cetus通过什么算法或者机制实现多个从库间分配读请求的负载均衡的？

**Comment by wangbin579** [comment]
目前算法比较简单，获取从库连接时，按照round robin法则去获取，如果不同连接的请求数量不同，可能负载就会不均衡。
一般而言，流量越大，越均衡。

从连接来计算，而不是请求的角度来做，主要为了性能考虑
