### ISSUE TITLE
一个sql，在数据库上正常， 通过cetus后，返回值不一致。cetus本身只保留了一个主库！

### ISSUE THREAD

**Issue by majq1990** [session-replay-tools/cetus#217]
![lALPDgfLS588Xf_NAb_NBUI_1346_447](https://user-images.githubusercontent.com/29979847/137427443-550b489d-1e20-44bc-b970-137a53ff386b.png)
cetus只有一个库
但是，日志可以看到，同一个sql，一会1条，一会21条
![image](https://user-images.githubusercontent.com/29979847/137427543-722cc7c7-1178-4f1e-9bbc-e70f907a8e75.png)
![image](https://user-images.githubusercontent.com/29979847/137427569-ad7f3e18-17e3-4876-9459-16a989f2b97a.png)

确认sql是一致的

**Comment by wangbin579** [comment]
既然是一个主库，所有sql都会转发给这个主库，cetus只是代理返回，不会更改数据。
因此除非跟连接的模式有关系，否则应该是一样的，上面全量日志也只是记录了后端的响应。

最好通过抓包分析的方式来捕获后端主库的响应为啥不一样

**Comment by majq1990** [comment]
后端问题
