### ISSUE TITLE
Cetus对存在longtext的字段的表数据查询和插入报2013连接丢失错误

### ISSUE THREAD

**Issue by qianwuzheng** [session-replay-tools/cetus#218]
1、插入超10M的信息到longtext字段报2013 数据库连接丢失错误 （python3.7, orm:SQLalchemy, mysql8.0.21）
2、在高并发的场景下查询涉及longtext字段的表也会偶尔出现2013 错误，数据库连接丢失错误 (java,JPA, mysql8.0.21)

**Comment by wangbin579** [comment]
这个问题我有空测试一下，看看原因
