### ISSUE TITLE
在el8环境下编译报错

### ISSUE THREAD

**Issue by majq1990** [session-replay-tools/cetus#219]
我参考
https://github.com/session-replay-tools/cetus/blob/master/doc/cetus-rpm.md
进行rpm打包时候，报错：

In file included from /root/rpmbuild/BUILD/cetus-2/src/network-mysqld-packet.c:29:
/root/rpmbuild/BUILD/cetus-2/src/network-mysqld-packet.c: In function 'network_mysqld_proto_get_com_qu
ery_result':/root/rpmbuild/BUILD/cetus-2/src/network-mysqld-packet.h:103:36: error: 'SERVER_MORE_RESULTS_EXIST' un
declared (first use in this function); did you mean 'SERVER_MORE_RESULTS_EXISTS'? #define SERVER_MORE_RESULTS_EXISTS SERVER_MORE_RESULTS_EXIST
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
/root/rpmbuild/BUILD/cetus-2/src/network-mysqld-packet.c:98:50: note: in expansion of macro 'SERVER_MO
RE_RESULTS_EXISTS'                 if (!(ok_packet->server_status & SERVER_MORE_RESULTS_EXISTS)) {
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
/root/rpmbuild/BUILD/cetus-2/src/network-mysqld-packet.h:103:36: note: each undeclared identifier is r
eported only once for each function it appears in #define SERVER_MORE_RESULTS_EXISTS SERVER_MORE_RESULTS_EXIST
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
/root/rpmbuild/BUILD/cetus-2/src/network-mysqld-packet.c:98:50: note: in expansion of macro 'SERVER_MO
RE_RESULTS_EXISTS'                 if (!(ok_packet->server_status & SERVER_MORE_RESULTS_EXISTS)) {
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
/root/rpmbuild/BUILD/cetus-2/src/network-mysqld-packet.c: In function 'network_mysqld_proto_get_query_
result':/root/rpmbuild/BUILD/cetus-2/src/network-mysqld-packet.c:685:10: error: 'COM_SHUTDOWN' undeclared (fir
st use in this function); did you mean 'COM_DAEMON'?     case COM_SHUTDOWN:
          ^~~~~~~~~~~~
          COM_DAEMON
make[2]: *** [src/CMakeFiles/mysql-chassis-proxy.dir/build.make:104: src/CMakeFiles/mysql-chassis-prox
y.dir/network-mysqld-packet.c.o] Error 1make[1]: *** [CMakeFiles/Makefile2:981: src/CMakeFiles/mysql-chassis-proxy.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.rLS9qF (%install)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.rLS9qF (%install)

**Comment by majq1990** [comment]
有没有大佬遇到过？编译安装一样的报错。。

**Comment by net592** [comment]
:-) 您好，收到了 ，尽快恢复

**Comment by majq1990** [comment]
强制将5.7的mysql-devel，el7版本，安装到el8上，可以编译安装。
但是打包提示：
[ 60%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/resultset_merge.c.o
In function 'merge_aggr_value',
    inlined from 'modify_record.isra.21' at /root/rpmbuild/BUILD/cetus-2/src/resultset_merge.c:1109:10:
/root/rpmbuild/BUILD/cetus-2/src/resultset_merge.c:1057:17: warning: 'strncpy' specified bound depends 
on the length of the source argument [-Wstringop-overflow=]                 strncpy(merged_value, str2, len2);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/rpmbuild/BUILD/cetus-2/src/resultset_merge.c: In function 'modify_record.isra.21':
/root/rpmbuild/BUILD/cetus-2/src/resultset_merge.c:1108:16: note: length computed here
     int len2 = strlen(str2);
                ^~~~~~~~~~~~
In function 'merge_aggr_value',
    inlined from 'modify_record.isra.21' at /root/rpmbuild/BUILD/cetus-2/src/resultset_merge.c:1109:10:
/root/rpmbuild/BUILD/cetus-2/src/resultset_merge.c:1040:17: warning: 'strncpy' specified bound depends 
on the length of the source argument [-Wstringop-overflow=]                 strncpy(merged_value, str2, len2);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/rpmbuild/BUILD/cetus-2/src/resultset_merge.c: In function 'modify_record.isra.21':
/root/rpmbuild/BUILD/cetus-2/src/resultset_merge.c:1108:16: note: length computed here
     int len2 = strlen(str2);
                ^~~~~~~~~~~~
In function 'merge_aggr_value',
    inlined from 'modify_record.isra.21' at /root/rpmbuild/BUILD/cetus-2/src/resultset_merge.c:1109:10:
/root/rpmbuild/BUILD/cetus-2/src/resultset_merge.c:1007:13: warning: 'strncpy' specified bound depends 
on the length of the source argument [-Wstringop-overflow=]             strncpy(merged_value, str1, len1);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/rpmbuild/BUILD/cetus-2/src/resultset_merge.c: In function 'modify_record.isra.21':
/root/rpmbuild/BUILD/cetus-2/src/resultset_merge.c:1107:16: note: length computed here
     int len1 = strlen(str1);
                ^~~~~~~~~~~~
In function 'merge_aggr_value',
    inlined from 'modify_record.isra.21' at /root/rpmbuild/BUILD/cetus-2/src/resultset_merge.c:1109:10:
/root/rpmbuild/BUILD/cetus-2/src/resultset_merge.c:1003:13: warning: 'strncpy' specified bound depends 
on the length of the source argument [-Wstringop-overflow=]             strncpy(merged_value, str2, len2);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/rpmbuild/BUILD/cetus-2/src/resultset_merge.c: In function 'modify_record.isra.21':
/root/rpmbuild/BUILD/cetus-2/src/resultset_merge.c:1108:16: note: length computed here
     int len2 = strlen(str2);
                ^~~~~~~~~~~~
[ 61%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/cetus-log.c.o
[ 62%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/cetus-setaffinity.c.o
[ 64%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/cetus-process.c.o
[ 65%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/cetus-process-cycle.c.o
[ 66%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/cetus-channel.c.o
[ 67%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/plugin-common.c.o
[ 69%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/network-backend.c.o
[ 70%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/sharding-config.c.o
[ 71%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/sharding-query-plan.c.o
[ 73%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/shard-plugin-con.c.o
[ 74%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/character-set.c.o
[ 75%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/server-session.c.o
[ 76%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/network-compress.c.o
[ 78%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/cetus-users.c.o
[ 79%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/cetus-util.c.o
[ 80%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/cetus-variable.c.o
[ 82%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/cetus-monitor.c.o
[ 83%] Building C object src/CMakeFiles/mysql-chassis-proxy.dir/cetus-acl.c.o
[ 84%] Linking C shared library libmysql-chassis-proxy.so
[ 84%] Built target mysql-chassis-proxy
[ 85%] Building C object src/CMakeFiles/cetus.dir/mysql-proxy-cli.c.o
[ 87%] Linking C executable cetus
[ 87%] Built target cetus
[ 88%] Generating admin-parser.y.c
[ 89%] [FLEX][AdminLexer] Building scanner with flex 2.6.1
[ 91%] Building C object plugins/admin/CMakeFiles/admin.dir/admin-plugin.c.o
/root/rpmbuild/BUILD/cetus-2/plugins/admin/admin-plugin.c: In function 'construct_channel_info':
/root/rpmbuild/BUILD/cetus-2/plugins/admin/admin-plugin.c:422:9: warning: 'strncpy' specified bound dep
ends on the length of the source argument [-Wstringop-overflow=]         strncpy(ch.admin_sql, sql, len);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/rpmbuild/BUILD/cetus-2/plugins/admin/admin-plugin.c:416:15: note: length computed here
     int len = strlen(sql);
               ^~~~~~~~~~~
/root/rpmbuild/BUILD/cetus-2/plugins/admin/admin-plugin.c: In function 'check_allowed_running':
/root/rpmbuild/BUILD/cetus-2/plugins/admin/admin-plugin.c:874:9: warning: 'strncpy' specified bound dep
ends on the length of the source argument [-Wstringop-overflow=]         strncpy(un.sun_path, name, strlen(name));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/rpmbuild/BUILD/cetus-2/plugins/admin/admin-plugin.c:871:9: note: length computed here
     if (strlen(name) >= sizeof(un.sun_path)) {
         ^~~~~~~~~~~~
[ 92%] Building C object plugins/admin/CMakeFiles/admin.dir/admin-commands.c.o
[ 93%] Building C object plugins/admin/CMakeFiles/admin.dir/admin-stats.c.o
[ 94%] Building C object plugins/admin/CMakeFiles/admin.dir/admin-lexer.l.c.o
[ 96%] Building C object plugins/admin/CMakeFiles/admin.dir/admin-parser.y.c.o
[ 97%] Linking C shared library libadmin.so
[ 97%] Built target admin
[ 98%] Building C object plugins/proxy/CMakeFiles/proxy.dir/proxy-plugin.c.o
[100%] Linking C shared library libproxy.so
[100%] Built target proxy
Install the project...
-- Install configuration: "Release"
-- Installing: /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/pkgconfig/mysql-chas
sis.pc-- Installing: /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/pkgconfig/cetus.pc
-- Installing: /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/logs/README_XA
-- Installing: /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/conf/users.json.example
-- Installing: /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/conf/variables.json.exam
ple-- Installing: /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/conf/sharding.json.examp
le-- Installing: /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/conf/shard.conf.example
-- Installing: /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/conf/proxy.conf.example
-- Installing: /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/libev-cetus.so
-- Installing: /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/bin/cetus
-- Installing: /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/libexec/cetus
-- Set runtime path of "/root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/libexec/cetus" 
to ""-- Installing: /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/libmysql-chassis.so
-- Set runtime path of "/root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/libmysql-ch
assis.so" to ""-- Installing: /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/libmysql-chassis-pro
xy.so-- Set runtime path of "/root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/libmysql-ch
assis-proxy.so" to ""-- Installing: /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/libmysql-chassis-gli
bext.so-- Set runtime path of "/root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/libmysql-ch
assis-glibext.so" to ""-- Installing: /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/libmysql-chassis-tim
ing.so-- Set runtime path of "/root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/libmysql-ch
assis-timing.so" to ""-- Installing: /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/cetus/plugins/libadm
in.so-- Set runtime path of "/root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/cetus/plugi
ns/libadmin.so" to ""-- Installing: /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/cetus/plugins/libpro
xy.so-- Set runtime path of "/root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/cetus/plugi
ns/libproxy.so" to ""-- Installing: /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/libsqlparser.so
+ /usr/lib/rpm/find-debuginfo.sh -j4 --strict-build-id -m -i --build-id-seed 2-3.9.el8 --unique-debug-s
uffix -2-3.9.el8.x86_64 --unique-debug-src-base cetus-2-3.9.el8.x86_64 --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 110000000 -S debugsourcefiles.list /root/rpmbuild/BUILD/cetus-2extracting debug info from /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/cetus/pl
ugins/libadmin.soextracting debug info from /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/libmysql
-chassis-glibext.soextracting debug info from /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/cetus/pl
ugins/libproxy.soextracting debug info from /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/libev-ce
tus.sogdb-add-index: No index was created for /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus
/lib/libmysql-chassis-glibext.sogdb-add-index: [Was there no debuginfo? Was there already an index?]
gdb-add-index: No index was created for /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus
/lib/cetus/plugins/libproxy.sogdb-add-index: [Was there no debuginfo? Was there already an index?]
gdb-add-index: No index was created for /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus
/lib/libev-cetus.sogdb-add-index: [Was there no debuginfo? Was there already an index?]
gdb-add-index: No index was created for /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus
/lib/cetus/plugins/libadmin.sogdb-add-index: [Was there no debuginfo? Was there already an index?]
extracting debug info from /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/libmysql
-chassis-proxy.soextracting debug info from /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/libmysql
-chassis-timing.soextracting debug info from /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/libmysql
-chassis.soextracting debug info from /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/lib/libsqlpa
rser.sogdb-add-index: No index was created for /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus
/lib/libmysql-chassis-timing.sogdb-add-index: [Was there no debuginfo? Was there already an index?]
gdb-add-index: No index was created for /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus
/lib/libmysql-chassis.sogdb-add-index: [Was there no debuginfo? Was there already an index?]
gdb-add-index: No index was created for /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus
/lib/libmysql-chassis-proxy.sogdb-add-index: [Was there no debuginfo? Was there already an index?]
gdb-add-index: No index was created for /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus
/lib/libsqlparser.sogdb-add-index: [Was there no debuginfo? Was there already an index?]
extracting debug info from /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus/libexec/cetu
sgdb-add-index: No index was created for /root/rpmbuild/BUILDROOT/cetus-2-3.9.el8.x86_64/usr/local/cetus
/libexec/cetusgdb-add-index: [Was there no debuginfo? Was there already an index?]
dwz: Too few files for multifile optimization
/usr/lib/rpm/sepdebugcrcfix: Updated 0 CRC32s, 9 CRC32s did match.
+ '[' '%{buildarch}' = noarch ']'
+ QA_CHECK_RPATHS=1
+ case "${QA_CHECK_RPATHS:-}" in
+ /usr/lib/rpm/check-rpaths
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-ldconfig
/sbin/ldconfig: Warning: ignoring configuration file that cannot be opened: /etc/ld.so.conf: No such fi
le or directory+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile '' 1
+ /usr/lib/rpm/brp-python-hardlink
+ PYTHON3=/usr/libexec/platform-python
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
Processing files: cetus-2-3.9.el8.x86_64
Provides: cetus = 2-3.9.el8 cetus(x86-64) = 2-3.9.el8 libadmin.so()(64bit) libev-cetus.so()(64bit) libm
ysql-chassis-glibext.so()(64bit) libmysql-chassis-proxy.so()(64bit) libmysql-chassis-timing.so()(64bit) libmysql-chassis.so()(64bit) libproxy.so()(64bit) libsqlparser.so()(64bit) pkgconfig(cetus) = 2.3.9 pkgconfig(mysql-chassis) = 2.3.9Requires(interp): /bin/sh /bin/sh
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadF
ilesHavePrefix) <= 4.0-1Requires(post): /bin/sh
Requires(postun): /bin/sh
Requires: /bin/sh /usr/bin/pkg-config libc.so.6()(64bit) libc.so.6(GLIBC_2.10)(64bit) libc.so.6(GLIBC_2
.14)(64bit) libc.so.6(GLIBC_2.17)(64bit) libc.so.6(GLIBC_2.2.5)(64bit) libc.so.6(GLIBC_2.3)(64bit) libc.so.6(GLIBC_2.3.2)(64bit) libc.so.6(GLIBC_2.4)(64bit) libc.so.6(GLIBC_2.7)(64bit) libc.so.6(GLIBC_2.9)(64bit) libdl.so.2()(64bit) libev-cetus.so()(64bit) libglib-2.0.so.0()(64bit) libgmodule-2.0.so.0()(64bit) libgthread-2.0.so.0()(64bit) libm.so.6()(64bit) libm.so.6(GLIBC_2.2.5)(64bit) libmysql-chassis-glibext.so()(64bit) libmysql-chassis-proxy.so()(64bit) libmysql-chassis-timing.so()(64bit) libmysql-chassis.so()(64bit) libmysqlclient.so.20()(64bit) libmysqlclient.so.20(libmysqlclient_20.0)(64bit) libpthread.so.0()(64bit) libpthread.so.0(GLIBC_2.2.5)(64bit) librt.so.1()(64bit) libsqlparser.so()(64bit) libz.so.1()(64bit) pkgconfig(glib-2.0) >= 2.16 pkgconfig(mysql-chassis) >= 2.3.9 rtld(GNU_HASH)Processing files: cetus-debugsource-2-3.9.el8.x86_64
error: Empty %files file /root/rpmbuild/BUILD/cetus-2/debugsourcefiles.list


RPM build errors:
    Empty %files file /root/rpmbuild/BUILD/cetus-2/debugsourcefiles.list

**Comment by majq1990** [comment]
解释一下，主要centos7不维护，阿里龙蜥又编译了一个centos8变成了alios8，搞得必须弄，哎

**Comment by majq1990** [comment]
修改了一下，可以了
![image](https://user-images.githubusercontent.com/29979847/194686527-a378c432-0de6-40fe-b12d-ec7d8dc9ee32.png)

**Comment by majq1990** [comment]
不编译debug，就可以正常通过，改一下编译的sh脚本即可
#!/bin/bash

basedir=$(pwd)

set -e

while getopts "v:r:s:h" arg
do
        case $arg in
             v)
                echo "version_no: $OPTARG"
                version_no=$OPTARG
		;;
             r)
                echo "release_no: $OPTARG"
		release_no=$OPTARG
                ;;
             s)
                echo "simple_parser: $OPTARG"
                simple_parser=$OPTARG
                ;;
	     h)
                echo "-v release_no -r release_no -s simple_parser"
		exit 0
		;;
             ?)
            	echo "unkown argument"
        	exit 1
        	;;
        esac
done

if [[ ! "${version_no}" ]] || [[ ! "${release_no}" ]];then
	echo "error argument, plese exec with '-v version_no -r release_no'"
	exit 1
fi

if [[ ! "${simple_parser}" ]];then
    simple_parser="1"
    echo "simple_parser: ${simple_parser}"
fi

rm -rf ~/rpmbuild/RPMS/x86_64/cetus-${version_no}-${release_no}.el8.x86_64.rpm
#rm -rf ~/rpmbuild/RPMS/x86_64/cetus-debuginfo-${version_no}-${release_no}.el8.x86_64.rpm
rm -rf ~/rpmbuild/SRPMS/cetus-${version_no}-${release_no}.el8.src.rpm

rm -rf ~/rpmbuild/SOURCES/cetus-${version_no}
rm -rf ~/rpmbuild/SPECS/cetus-${version_no}.spec
mkdir ~/rpmbuild/SOURCES/cetus-${version_no}
cp -rf ../* ~/rpmbuild/SOURCES/cetus-${version_no}
cp -rf ./cetus.spec ~/rpmbuild/SPECS/cetus-${version_no}.spec


sed -i "s/Version:.*/Version: ${version_no}/"  ~/rpmbuild/SPECS/cetus-${version_no}.spec
sed -i "s/Release:.*/Release: ${release_no}%{?dist}/" ~/rpmbuild/SPECS/cetus-${version_no}.spec
if [ ${simple_parser} -eq 0 ]; then
    sed -i "s/%define _simple_parser .*/%define _simple_parser off/" ~/rpmbuild/SPECS/cetus-${version_no}.spec
fi

cd ~/rpmbuild/SOURCES/
tar -zcf cetus-${version_no}.tar.gz cetus-${version_no}
cd ~
rpmbuild -ba ~/rpmbuild/SPECS/cetus-${version_no}.spec

cd $basedir
mv ~/rpmbuild/RPMS/x86_64/cetus-${version_no}-${release_no}.el8.x86_64.rpm ./
#mv ~/rpmbuild/RPMS/x86_64/cetus-debuginfo-${version_no}-${release_no}.el8.x86_64.rpm ./
mv ~/rpmbuild/SRPMS/cetus-${version_no}-${release_no}.el8.src.rpm ./

rm -rf ~/rpmbuild/SOURCES/cetus-${version_no}
rm -rf ~/rpmbuild/SOURCES/cetus-${version_no}.tar.gz
rm -rf ~/rpmbuild/BUILD/cetus-${version_no}
rm -rf ~/rpmbuild/SPECS/cetus-${version_no}.spec
