### ISSUE TITLE
src/network-mysqld.c:2589

### ISSUE THREAD

**Issue by larry2208** [session-replay-tools/cetus#221]
几台cetus server 总有一台报这个错，配置和其他服务是一样的。

(pid=10359) 2023-03-29 06:28:39: (critical) src/network-mysqld.c:2589: wait failed and no server backend for user:XX_user, ret:4
(pid=10359) 2023-03-29 06:29:03: (critical) last message repeated 8 times
(pid=10359) 2023-03-29 06:29:03: (critical) src/network-mysqld.c:2589: wait failed and no server backend for user:XX_user, ret:4
(pid=10359) 2023-03-29 06:29:03: (warning) plugins/proxy/proxy-plugin.c:1681 server_to_be_closed is true
(pid=10359) 2023-03-29 06:29:05: (critical) src/network-mysqld.c:2589: wait failed and no server backend for user:XX_user, ret:4
(pid=10359) 2023-03-29 06:29:05: (warning) plugins/proxy/proxy-plugin.c:1681 server_to_be_closed is true
(pid=10359) 2023-03-29 06:29:07: (critical) src/network-mysqld.c:2589: wait failed and no server backend for XX_user, ret:4
(pid=10359) 2023-03-29 06:29:28: (warning) last message repeated 1 times
(pid=10359) 2023-03-29 06:29:28: (warning) plugins/proxy/proxy-plugin.c:587: charset code:33, charset:utf8
(pid=10359) 2023-03-29 06:29:56: (critical) src/network-mysqld.c:2589: wait failed and no server backend for user:XX_user, ret:4

**Comment by net592** [comment]
:-) 您好，收到了 ，尽快恢复

**Comment by wangbin579** [comment]
这个可能跟后端mysql连接不上导致的，最好通过抓包分析一下

**Comment by net592** [comment]
:-) 您好，收到了 ，尽快恢复

**Comment by wangbin579** [comment]
几台中总有一台报这个错，是固定一台，还是都有可能出现

**Comment by larry2208** [comment]
最近很久没有报错了。最后出现错误 是3台cetus 服务，中的一台一直报错，没有找到原因，就恢复了。 
之前也曽出现过是当max-pool-size 没给太大值，后端cetus 全都会报这个错误，调大后异常解决。
看了下源码，感觉是除了几种异常，其他的任何连通异常都会报这个错误。

**Comment by wangbin579** [comment]
如果是一直一台报错，可能原因是：
1、配置文件中的连接数量是否设置过小
2、是否跟环境相关
3、这台机器的流量是否跟其它有差别

当然如果有抓包分析数据，那就非常好分析了。

**Comment by wangbin579** [comment]
如果访问db的用户过多，default-pool-size设置太小，会导致某些用户分配不到连接，也会报上述错误。

**Comment by larry2208** [comment]
可以close了，确实是 default-pool-size  的问题，调大后，问题解决
