### ISSUE TITLE
请问为什么后端的数据库状态是unknow呢

### ISSUE THREAD

**Issue by xuge233** [session-replay-tools/cetus#222]
![image](https://github.com/session-replay-tools/cetus/assets/80495147/329e0c28-2a43-42c5-b2af-b17c82927696)
还有一个问题，我看配置文件的参数没有涉及到数据库密码，是怎么和mysql进行连接的呢

**Comment by wangbin579** [comment]
有专门的配置配置用户名和密码的。
unknown问题，跟连接不上相关
