### ISSUE TITLE
读写分离模式下数据库连接异常：client charset is not supported

### ISSUE THREAD

**Issue by canglangdahai** [session-replay-tools/cetus#224]
操作系统：ubuntu20.04
mysql版本：8.0.33，mysqld.cnf中配置了default-character-set=utf8mb4
cetus版本：2.4.0，proxy.conf已配置了default-charset=utf8mb4
连接数据库时总是失败，提示：client charset is not supported
查看日志：src/plugin-common.c:239: client charset is nil, orig charset num:255

**Comment by net592** [comment]
:-) 您好，收到了 ，尽快恢复

**Comment by dreamalloc** [comment]
如果要使用mysql8客户端访问cetus的服务端，需要添加以下配置：MySQL8 默认使用utf8mb4字符集，而MySQL5.7默认使用utf8字符集。确保客户端配置与服务器的字符集和排序规则兼容。在连接字符串中，可以使用 --default-character-set 选项来指定字符集
mysql -h 192.168.65.134 -u user-p --default-character-set=utf8

或者在my.cnf中添加
[client]
default-character-set=utf8
