### ISSUE TITLE
参考proxysql，实现一致性读

### ISSUE THREAD

**Issue by lazio579** [session-replay-tools/cetus#31]
http://www.proxysql.com/blog/proxysql-gtid-causal-reads

**Comment by lazio579** [comment]
包括读写分离，query cache都必须要实现强一致性读

**Comment by pho7001** [comment]
您好，能不能接mysql group replication?实现MGR的读写分离？？

**Comment by lazio579** [comment]
@pho7001 ，对单主情况下的mgr，我们正在开发中，正常情况下，6月份会出来

**Comment by pho7001** [comment]
期待中，到时候我也会测试

2018-04-17 17:55 GMT+08:00 wangbin <notifications@github.com>:
